src/main/java/project/jssi_education/entity/Administrator.java
src/main/java/project/jssi_education/entity/Manager.java
src/main/java/project/jssi_education/entity/Student.java
src/main/java/project/jssi_education/entity/Teacher.java
src/main/java/project/jssi_education/entity/User.java

Add entity classes

---

src/main/java/project/jssi_education/entity/Administrator.java
src/main/java/project/jssi_education/entity/Manager.java
src/main/java/project/jssi_education/entity/Student.java
src/main/java/project/jssi_education/entity/Teacher.java
src/main/java/project/jssi_education/entity/User.java

change entity package

---

pom.xml

change pom.xml file

---

src/main/java/project/jssi_education/entity/Administrator.java
src/main/java/project/jssi_education/entity/Manager.java
src/main/java/project/jssi_education/entity/Student.java
src/main/java/project/jssi_education/entity/Teacher.java

remove extends from student, teacher, manager, administrator

Fix entity classes

---

.idea/misc.xml
pom.xml

removed the thymeleaf dependency from the pom.xml

removed a dependency

---

src/main/java/project/jssi_education/entity/Administrator.java
src/main/java/project/jssi_education/entity/Manager.java
src/main/java/project/jssi_education/entity/Student.java
src/main/java/project/jssi_education/entity/Teacher.java
src/main/resources/application.properties

add id to classes

---

src/main/resources/application.properties

Configured MySQL database connection settings.

Modify application.properties for DB connection

---

src/main/java/project/jssi_education/entity/Attendance.java
src/main/java/project/jssi_education/entity/Course.java
src/main/java/project/jssi_education/entity/Enrrollment.java
src/main/java/project/jssi_education/entity/Grade.java
src/main/java/project/jssi_education/entity/Group.java
src/main/java/project/jssi_education/entity/Schedule.java

add new classes

---

src/main/java/project/jssi_education/repository/IAdministratorRepository.java
src/main/java/project/jssi_education/repository/IAttendanceRepository.java
src/main/java/project/jssi_education/repository/ICourseRepository.java
src/main/java/project/jssi_education/repository/IEnrollmentRepository.java
src/main/java/project/jssi_education/repository/IGradeRepository.java
src/main/java/project/jssi_education/repository/IGroupRepository.java
src/main/java/project/jssi_education/repository/IManagerRepository.java
src/main/java/project/jssi_education/repository/IScheduleRepository.java
src/main/java/project/jssi_education/repository/IStudentRepository.java
src/main/java/project/jssi_education/repository/ITeacherRepository.java
src/main/java/project/jssi_education/repository/IUserRepository.java

Add repository package and its repository classes

Add new package and classes

---

src/main/java/project/jssi_education/service/IAdministratorService.java
src/main/java/project/jssi_education/service/IAttendanceService.java
src/main/java/project/jssi_education/service/ICourseService.java
src/main/java/project/jssi_education/service/IEnrollmentService.java
src/main/java/project/jssi_education/service/IGradeService.java
src/main/java/project/jssi_education/service/IGroupService.java
src/main/java/project/jssi_education/service/IManagerService.java
src/main/java/project/jssi_education/service/IScheduleService.java
src/main/java/project/jssi_education/service/IStudentService.java
src/main/java/project/jssi_education/service/ITeacherService.java
src/main/java/project/jssi_education/service/IUserService.java
src/main/java/project/jssi_education/service/impl/AdministratorService.java
src/main/java/project/jssi_education/service/impl/AttendanceService.java
src/main/java/project/jssi_education/service/impl/CourseService.java
src/main/java/project/jssi_education/service/impl/EnrollmentService.java
src/main/java/project/jssi_education/service/impl/GradeService.java
src/main/java/project/jssi_education/service/impl/GroupService.java
src/main/java/project/jssi_education/service/impl/ManagerService.java
src/main/java/project/jssi_education/service/impl/ScheduleService.java
src/main/java/project/jssi_education/service/impl/StudentService.java
src/main/java/project/jssi_education/service/impl/TeacherService.java
src/main/java/project/jssi_education/service/impl/UserService.java

add service package

---

src/main/java/project/jssi_education/entity/Attendance.java
src/main/java/project/jssi_education/entity/Course.java
src/main/java/project/jssi_education/entity/Enrollment.java
src/main/java/project/jssi_education/entity/Enrrollment.java
src/main/java/project/jssi_education/entity/Grade.java
src/main/java/project/jssi_education/entity/Group.java
src/main/java/project/jssi_education/repository/IEnrollmentRepository.java

add atributes in entity classes

add new atributes

---

src/main/java/project/jssi_education/entity/Administrator.java
src/main/java/project/jssi_education/entity/Attendance.java
src/main/java/project/jssi_education/entity/Course.java
src/main/java/project/jssi_education/entity/Enrollment.java
src/main/java/project/jssi_education/entity/Grade.java
src/main/java/project/jssi_education/entity/Group.java
src/main/java/project/jssi_education/entity/Manager.java
src/main/java/project/jssi_education/entity/Schedule.java
src/main/java/project/jssi_education/entity/Student.java
src/main/java/project/jssi_education/entity/Teacher.java
src/main/java/project/jssi_education/entity/User.java

Changed the data type of "id" fields from "int" to "Long"
-Added `@Id` and `@GeneratedValue` annotations to the `id` fields

Update Annotations in Classes within the `entity` Package

---

src/main/resources/static/css/styles.css
src/main/resources/static/indexUser.html

Add new part of the main page and info within this

Add footer main page

---

src/main/resources/academicCalendar.html

add new page file

---

src/main/resources/static/css/calendar.css

add styles for academicCalendar.html

add styles file

---

src/main/resources/static/js/calendar.js

add new js file

---

src/main/resources/academicCalendar.html

add details and info calendar page

add calendar details

---

src/main/resources/static/academicCalendar.html
src/main/resources/static/css/admin.css
src/main/resources/static/indexAdmin.html
src/main/resources/static/indexUser.html

Add new page

---

pom.xml
src/main/resources/application.properties

Update database configuration in application.properties

Change the application.properties file

---

src/main/resources/templates/academicCalendar.html
src/main/resources/templates/indexAdmin.html
src/main/resources/templates/indexUser.html

change rutes in the html files

change html files

---

src/main/resources/static/css/currentGrades.css
src/main/resources/static/css/updateForm.css
src/main/resources/static/js/updateForm.js
src/main/resources/templates/currentGrades.html
src/main/resources/templates/updateForm.html

Add new form page for data update functionality.

Create update data form page and course grades table page

---

src/main/java/project/jssi_education/entity/EmploymentContract.java
src/main/java/project/jssi_education/entity/Manager.java
src/main/java/project/jssi_education/entity/Teacher.java
src/main/java/project/jssi_education/entity/User.java

Implement relationships in some entities

Add relationships between entities

---

src/main/java/project/jssi_education/entity/Degree.java
src/main/java/project/jssi_education/entity/Student.java
src/main/java/project/jssi_education/service/IDegreeService.java
src/main/java/project/jssi_education/service/impl/DegreeService.java

add class degree and entity relations with student

Add class degree

---

src/main/java/project/jssi_education/controller/CourseController.java
src/main/java/project/jssi_education/controller/DegreeController.java
src/main/java/project/jssi_education/controller/GroupController.java
src/main/java/project/jssi_education/controller/ManagerController.java
src/main/java/project/jssi_education/controller/StudentController.java
src/main/java/project/jssi_education/controller/TeacherController.java
src/main/java/project/jssi_education/controller/UserController.java

Add controllers for entities with no functionality

Create Empty Controllers for Entities

---

src/main/java/project/jssi_education/entity/Course.java
src/main/java/project/jssi_education/entity/DegreeCourse.java

Create DegreeCourse entity as intermediary table and update Degree and Course classes.

Add many-to-many relationship between Degree and Course

---

src/main/java/project/jssi_education/repository/IDegreeRepository.java

add repository

---

src/main/java/project/jssi_education/entity/DayWeek.java
src/main/java/project/jssi_education/entity/Group.java
src/main/java/project/jssi_education/entity/Offer.java
src/main/java/project/jssi_education/entity/Teacher.java

add entity offer and dayWeek with their relationships

add new entitys

---

src/main/java/project/jssi_education/entity/Course.java
src/main/java/project/jssi_education/entity/Semester.java

add new entity semester with their relationships

add new entity

---

src/main/java/project/jssi_education/repository/IAdministratorRepository.java
src/main/java/project/jssi_education/repository/IAttendanceRepository.java
src/main/java/project/jssi_education/repository/ICourseRepository.java
src/main/java/project/jssi_education/repository/IDegreeRepository.java
src/main/java/project/jssi_education/repository/IEnrollmentRepository.java
src/main/java/project/jssi_education/repository/IGradeRepository.java
src/main/java/project/jssi_education/repository/IGroupRepository.java
src/main/java/project/jssi_education/repository/IManagerRepository.java
src/main/java/project/jssi_education/repository/IScheduleRepository.java
src/main/java/project/jssi_education/repository/IStudentRepository.java
src/main/java/project/jssi_education/repository/ITeacherRepository.java
src/main/java/project/jssi_education/repository/IUserRepository.java
src/main/java/project/jssi_education/service/impl/AdministratorService.java
src/main/java/project/jssi_education/service/impl/AttendanceService.java
src/main/java/project/jssi_education/service/impl/CourseService.java
src/main/java/project/jssi_education/service/impl/DegreeService.java
src/main/java/project/jssi_education/service/impl/EnrollmentService.java
src/main/java/project/jssi_education/service/impl/GradeService.java
src/main/java/project/jssi_education/service/impl/GroupService.java
src/main/java/project/jssi_education/service/impl/ManagerService.java
src/main/java/project/jssi_education/service/impl/ScheduleService.java
src/main/java/project/jssi_education/service/impl/StudentService.java
src/main/java/project/jssi_education/service/impl/TeacherService.java
src/main/java/project/jssi_education/service/impl/UserService.java

Add annotations Service and Repository

Add annotations

---

src/main/java/project/jssi_education/entity/Administrator.java
src/main/java/project/jssi_education/entity/Attendance.java
src/main/java/project/jssi_education/entity/Course.java
src/main/java/project/jssi_education/entity/DayWeek.java
src/main/java/project/jssi_education/entity/Degree.java
src/main/java/project/jssi_education/entity/DegreeCourse.java
src/main/java/project/jssi_education/entity/EmploymentContract.java
src/main/java/project/jssi_education/entity/Enrollment.java
src/main/java/project/jssi_education/entity/Grade.java
src/main/java/project/jssi_education/entity/Group.java
src/main/java/project/jssi_education/entity/GroupStudent.java
src/main/java/project/jssi_education/entity/Manager.java
src/main/java/project/jssi_education/entity/Offer.java
src/main/java/project/jssi_education/entity/Schedule.java
src/main/java/project/jssi_education/entity/Semester.java
src/main/java/project/jssi_education/entity/Student.java
src/main/java/project/jssi_education/entity/Teacher.java
src/main/java/project/jssi_education/entity/TeacherEvaluation.java
src/main/java/project/jssi_education/entity/User.java

Add @Table and @Entity annotations in relevant classes.

Add missing @Table and @Entity annotations

---

src/main/java/project/jssi_education/entity/Semester.java

Rename table and corrected field name from 'user' to 'semester' in Semester entity.

Fix table name and correct entity field name

---

src/main/java/project/jssi_education/entity/Teacher.java

change relationship between offer and teacher

change relationship

---

src/main/resources/static/css/students.css
src/main/resources/static/indexUser.html
src/main/resources/templates/academicCalendar.html
src/main/resources/templates/loginUser.html
src/main/resources/templates/studentsAdmin.html
src/main/resources/templates/updateForm.html

Add new form to add a new student as an administrator

Create new student form

---

src/main/java/project/jssi_education/entity/Administrator.java
src/main/java/project/jssi_education/entity/Attendance.java
src/main/java/project/jssi_education/entity/Course.java
src/main/java/project/jssi_education/entity/DayWeek.java
src/main/java/project/jssi_education/entity/Degree.java
src/main/java/project/jssi_education/entity/DegreeCourse.java
src/main/java/project/jssi_education/entity/EmploymentContract.java
src/main/java/project/jssi_education/entity/Enrollment.java
src/main/java/project/jssi_education/entity/Grade.java
src/main/java/project/jssi_education/entity/Group.java
src/main/java/project/jssi_education/entity/GroupStudent.java
src/main/java/project/jssi_education/entity/Manager.java
src/main/java/project/jssi_education/entity/Offer.java
src/main/java/project/jssi_education/entity/Schedule.java
src/main/java/project/jssi_education/entity/Semester.java
src/main/java/project/jssi_education/entity/Student.java
src/main/java/project/jssi_education/entity/Teacher.java
src/main/java/project/jssi_education/entity/TeacherEvaluation.java
src/main/java/project/jssi_education/entity/User.java

Add Serializable implementation to entity classes for better object serialization.

Modify entity classes to implement Serializable

---

src/main/java/project/jssi_education/entity/Group.java
src/main/java/project/jssi_education/entity/Teacher.java

Resolve issues in Teacher and Group entity classes.

Fix bugs in Teacher and Group classes

---

src/main/java/project/jssi_education/entity/Manager.java
src/main/java/project/jssi_education/entity/Student.java
src/main/java/project/jssi_education/entity/Teacher.java
src/main/java/project/jssi_education/entity/User.java

change relationship to studet, teacher and manager

Change relationships user

---

src/main/resources/static/css/students.css
src/main/resources/static/js/students.js
src/main/resources/templates/studentsAdmin.html

Remove create student form from html file to add it in js file

Remove create student form

---

src/main/java/project/jssi_education/entity/Administrator.java
src/main/java/project/jssi_education/entity/EmploymentContract.java
src/main/java/project/jssi_education/entity/Offer.java
src/main/java/project/jssi_education/entity/Teacher.java

Change relationships between Teacher, Admin, Offer, and EmploymentContract entities.

Update relationships in entities

---

src/main/java/project/jssi_education/controller/StudentController.java
src/main/java/project/jssi_education/service/IStudentService.java
src/main/java/project/jssi_education/service/IUserService.java
src/main/java/project/jssi_education/service/impl/StudentService.java
src/main/java/project/jssi_education/service/impl/UserService.java

add @override method for services

add unimplemented methods

---

src/main/java/project/jssi_education/controller/StudentController.java
src/main/java/project/jssi_education/exception/ResourceNotFoundException.java
src/main/java/project/jssi_education/service/impl/StudentService.java

add 404 (not found) exception to insert student

add 404 exception

---

src/main/java/project/jssi_education/entity/Enrollment.java
src/main/java/project/jssi_education/entity/Schedule.java
src/main/java/project/jssi_education/service/impl/EnrollmentService.java
src/main/java/project/jssi_education/service/impl/ScheduleService.java

remove classes

---

src/main/java/project/jssi_education/controller/StudentController.java
src/main/java/project/jssi_education/service/IStudentService.java
src/main/java/project/jssi_education/service/impl/StudentService.java

complete student crud

---

src/main/java/project/jssi_education/controller/TeacherController.java
src/main/java/project/jssi_education/service/ITeacherService.java
src/main/java/project/jssi_education/service/impl/TeacherService.java

Implement create, read, update, and delete for teachers

Implement Teacher CRUD Functionality

---

src/main/java/project/jssi_education/controller/ManagerController.java
src/main/java/project/jssi_education/service/IManagerService.java
src/main/java/project/jssi_education/service/impl/ManagerService.java

Add CRUD functionality for Manager

Implement CRUD functionality

---

src/main/java/project/jssi_education/controller/TeacherController.java
src/main/java/project/jssi_education/service/impl/TeacherService.java
src/main/resources/static/academicCalendar.html
src/main/resources/static/css/studentsPortal.css
src/main/resources/static/currentGrades.html
src/main/resources/static/index.html
src/main/resources/static/indexAdmin.html
src/main/resources/static/indexStudent.html
src/main/resources/static/js/teachers.js
src/main/resources/static/loginUser.html
src/main/resources/static/studentsAdmin.html
src/main/resources/static/teachersAdmin.html
src/main/resources/static/updateForm.html

Add the frontend for teacher management

Add Teacher CRUD frontend

---

src/main/java/project/jssi_education/repository/IDegreeCourseRepository.java

add necessary repository for course and degree

add degreeCourse repository

---

src/main/java/project/jssi_education/controller/SemesterController.java
src/main/java/project/jssi_education/entity/Semester.java
src/main/java/project/jssi_education/repository/ISemesterRepository.java
src/main/java/project/jssi_education/service/ISemesterService.java
src/main/java/project/jssi_education/service/impl/SemesterService.java

add (backend) crud for semester

---

src/main/java/project/jssi_education/controller/TeacherController.java
src/main/java/project/jssi_education/repository/ITeacherRepository.java
src/main/java/project/jssi_education/service/ITeacherService.java
src/main/java/project/jssi_education/service/impl/TeacherService.java
src/main/resources/static/js/teachers.js

Change search, delete and update to search teacher by idNumber

Fix(backend) CRUD for teacher

---

src/main/java/project/jssi_education/controller/CourseController.java
src/main/java/project/jssi_education/controller/DegreeCourseController.java
src/main/java/project/jssi_education/entity/Course.java
src/main/java/project/jssi_education/entity/DegreeCourse.java
src/main/java/project/jssi_education/repository/IDegreeCourseRepository.java
src/main/java/project/jssi_education/service/IDegreeCourseService.java
src/main/java/project/jssi_education/service/impl/DegreeCourseService.java

add (backend) crud

---

src/main/resources/static/css/manager.css
src/main/resources/static/indexManager.html
src/main/resources/static/js/teachers.js

Add a new index page for manager to manage contracts

Feat(frontend) add new index for Manager user

---

src/main/java/project/jssi_education/controller/GroupCourseController.java
src/main/java/project/jssi_education/repository/IGroupCourseRepository.java
src/main/java/project/jssi_education/service/IGroupCourseService.java
src/main/java/project/jssi_education/service/impl/GroupCourseService.java

Create for GroupCourse controller, service and interface

Add new classes(backend)

---

src/main/java/project/jssi_education/controller/ManagerController.java
src/main/java/project/jssi_education/service/IManagerService.java
src/main/java/project/jssi_education/service/impl/ManagerService.java

Add search, delete and update with IdNumber in Manager

Add new CRUD(backend)

---

src/main/java/project/jssi_education/entity/Grade.java

add attribute by note in Grade

Change attributes(backend)

---

src/main/java/project/jssi_education/controller/StudentController.java
src/main/java/project/jssi_education/service/IStudentService.java
src/main/java/project/jssi_education/service/IUserService.java
src/main/java/project/jssi_education/service/impl/StudentService.java
src/main/java/project/jssi_education/service/impl/UserService.java
src/main/resources/static/js/students.js

add create student functionality

 add (fronend) fuctionality

---

src/main/java/project/jssi_education/controller/StudentController.java
src/main/java/project/jssi_education/service/IStudentService.java
src/main/java/project/jssi_education/service/impl/StudentService.java
src/main/resources/static/js/students.js

add search by idNumber from view

add (frontend) student functionality

---

src/main/java/project/jssi_education/controller/ManagerController.java
src/main/java/project/jssi_education/repository/IManagerRepository.java
src/main/java/project/jssi_education/service/IManagerService.java
src/main/java/project/jssi_education/service/impl/ManagerService.java

fix data type in manager methods with idNumber

Fix methods in Manager(backend)

---

src/main/resources/static/js/managers.js

implement find a manager by idNumber

Implement CRUD Manager(frontend)

---

src/main/java/project/jssi_education/controller/StudentController.java
src/main/java/project/jssi_education/service/IStudentService.java
src/main/java/project/jssi_education/service/impl/StudentService.java
src/main/resources/static/js/students.js

add (frontend) update view

---

src/main/java/project/jssi_education/controller/ManagerController.java
src/main/resources/static/js/managers.js

Add delete by idNumber manager from view

Add functionality(frontend)

---

src/main/resources/static/indexAdmin.html

Change in header of indexAdmin

Change in view(frontend)

---

pom.xml
src/main/java/project/jssi_education/controller/DegreeController.java
src/main/java/project/jssi_education/controller/GradeController.java
src/main/java/project/jssi_education/controller/GroupController.java
src/main/java/project/jssi_education/controller/GroupCourseController.java
src/main/java/project/jssi_education/controller/OfferController.java
src/main/java/project/jssi_education/controller/OfferDayWeekController.java
src/main/java/project/jssi_education/entity/DidacticMaterial.java
src/main/java/project/jssi_education/repository/IGradeRepository.java
src/main/java/project/jssi_education/service/IDegreeService.java
src/main/java/project/jssi_education/service/IGradeService.java
src/main/java/project/jssi_education/service/IStudentService.java
src/main/java/project/jssi_education/service/impl/DegreeService.java
src/main/java/project/jssi_education/service/impl/GradeService.java
src/main/java/project/jssi_education/service/impl/StudentService.java
src/main/resources/static/indexStudent.html
src/main/resources/static/js/indexStudent.js

Refactored found methods and variables to camelCase

Standardized methods and variables (backend)

---

src/main/java/project/jssi_education/entity/EmploymentContract.java
src/main/java/project/jssi_education/service/impl/UserService.java
src/main/resources/static/css/teacher.css
src/main/resources/static/indexTeacher.html
src/main/resources/static/js/manager.js

Implement index page for teachers

Feat(Frontend): Add index for Teacher

---

src/main/java/project/jssi_education/entity/User.java

add (backend) user attribute

---

src/main/resources/static/css/degree.css
src/main/resources/static/degrees.html
src/main/resources/static/index.html
src/main/resources/static/js/degrees.js

Add functionality to display available degrees.

Feat(Frontend): Add page to view existing degrees

---

src/main/resources/static/courseAdmin.html
src/main/resources/static/indexAdmin.html
src/main/resources/static/js/courses.js

Implements CRUD functionality for Course

Add CRUD Course(frontend)

---

src/main/java/project/jssi_education/controller/IndexController.java
src/main/java/project/jssi_education/entity/User.java
src/main/resources/static/loginUser.html

Implement user login feature with authentication and session management.

Add login functionality

---

src/main/resources/static/courseAdmin.html
src/main/resources/static/groupAdmin.html
src/main/resources/static/indexAdmin.html
src/main/resources/static/managerAdmin.html
src/main/resources/static/studentsAdmin.html
src/main/resources/static/teachersAdmin.html

Add links to groupAdmin and courseAdmin HTML

Implements HTML links

---

src/main/java/project/jssi_education/entity/Attendance.java
src/main/java/project/jssi_education/entity/Student.java
src/main/java/project/jssi_education/entity/TeacherEvaluation.java

change (backend) teacher_evaluation and attendance

---

src/main/java/project/jssi_education/service/impl/TeacherService.java
src/main/resources/static/indexTeacher.html

Set user role to teacher during insertion

Fix(backend) assign role teacher

---

src/main/resources/static/js/teachers.js

Remove ID type input in create teacher form

Fix(frontend): remove one form input

---

src/main/java/project/jssi_education/controller/IndexController.java
src/main/java/project/jssi_education/service/impl/UserService.java
src/main/java/project/jssi_education/util/PasswordUtil.java

Add (backend) password feature

---

src/main/java/project/jssi_education/controller/PasswordRecoveryController.java
src/main/java/project/jssi_education/repository/IUserRepository.java
src/main/java/project/jssi_education/service/IUserService.java
src/main/java/project/jssi_education/service/impl/UserService.java
src/main/resources/static/css/recoverPasswd.css
src/main/resources/static/js/mainPage.js
src/main/resources/static/js/recoverPassword.js
src/main/resources/static/loginUser.html
src/main/resources/static/recover-password.html

Add (backend/frontend) feature

---

src/main/resources/templates/indexTeacher.html

Update indexTeacher to render associated information

Feature(Frontend): Update index to show information

---

src/main/java/project/jssi_education/controller/IndexController.java

Add a character to class IndexController

Fix(backend) bug

---

src/main/java/project/jssi_education/controller/IndexController.java
src/main/java/project/jssi_education/controller/UserProfileController.java
src/main/resources/templates/profile.html

 Fix (backend) password feature

---

src/main/java/project/jssi_education/service/impl/ManagerService.java

Add attribute User(backend)

---

src/main/java/project/jssi_education/controller/DidacticMaterialController.java
src/main/java/project/jssi_education/repository/IGroupCourseRepository.java
src/main/java/project/jssi_education/service/impl/DidacticMaterialService.java
src/main/java/project/jssi_education/service/impl/GroupCourseService.java
src/main/resources/static/js/didacticMaterial.js
src/main/resources/templates/indexTeacher.html

Implement create form for didactic materials

Feat(backend/frontend): add form

---

src/main/resources/static/js/courses.js

Change in insert and update from course

Change CRUD Course(frontend)

---

src/main/java/project/jssi_education/controller/OfferDayWeekController.java
src/main/java/project/jssi_education/repository/ITeacherEvaluationRepository.java
src/main/java/project/jssi_education/service/ITeacherEvaluationService.java
src/main/java/project/jssi_education/service/impl/AttendanceService.java
src/main/java/project/jssi_education/service/impl/OfferDayWeekService.java
src/main/java/project/jssi_education/service/impl/TeacherEvaluationService.java

Fix delete in controller and service in OfferDayWeek

Fix CRUD Offer(backend)
